// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ArabWaha.Employer.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ar {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ar() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ArabWaha.Employer.Resx.AppResources.ar", typeof(AppResources_ar).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonAddNewPost {
            get {
                return ResourceManager.GetString("ButtonAddNewPost", resourceCulture);
            }
        }
        
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        internal static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        internal static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        internal static string ButtonConfirmDelete {
            get {
                return ResourceManager.GetString("ButtonConfirmDelete", resourceCulture);
            }
        }
        
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        internal static string ButtonDeleteJobPost {
            get {
                return ResourceManager.GetString("ButtonDeleteJobPost", resourceCulture);
            }
        }
        
        internal static string ButtonDiscardChanges {
            get {
                return ResourceManager.GetString("ButtonDiscardChanges", resourceCulture);
            }
        }
        
        internal static string ButtonEditJobPost {
            get {
                return ResourceManager.GetString("ButtonEditJobPost", resourceCulture);
            }
        }
        
        internal static string ButtonInfoConfirmSaveChanges {
            get {
                return ResourceManager.GetString("ButtonInfoConfirmSaveChanges", resourceCulture);
            }
        }
        
        internal static string ButtonInfoDiscardChanges {
            get {
                return ResourceManager.GetString("ButtonInfoDiscardChanges", resourceCulture);
            }
        }
        
        internal static string ButtonSaveEdits {
            get {
                return ResourceManager.GetString("ButtonSaveEdits", resourceCulture);
            }
        }
        
        internal static string ButtonSignIn {
            get {
                return ResourceManager.GetString("ButtonSignIn", resourceCulture);
            }
        }
        
        internal static string ButtonSignUp {
            get {
                return ResourceManager.GetString("ButtonSignUp", resourceCulture);
            }
        }
        
        internal static string ButtonViewMatchingCandidates {
            get {
                return ResourceManager.GetString("ButtonViewMatchingCandidates", resourceCulture);
            }
        }
        
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        internal static string ClosedOn {
            get {
                return ResourceManager.GetString("ClosedOn", resourceCulture);
            }
        }
        
        internal static string ComplaintId {
            get {
                return ResourceManager.GetString("ComplaintId", resourceCulture);
            }
        }
        
        internal static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        internal static string Dateofbirth {
            get {
                return ResourceManager.GetString("Dateofbirth", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        internal static string FORGOTPASSRETRIEVEMETHOD {
            get {
                return ResourceManager.GetString("FORGOTPASSRETRIEVEMETHOD", resourceCulture);
            }
        }
        
        internal static string IndicatorRefreshText {
            get {
                return ResourceManager.GetString("IndicatorRefreshText", resourceCulture);
            }
        }
        
        internal static string LabelAccept {
            get {
                return ResourceManager.GetString("LabelAccept", resourceCulture);
            }
        }
        
        internal static string LabelAdditionalDetails {
            get {
                return ResourceManager.GetString("LabelAdditionalDetails", resourceCulture);
            }
        }
        
        internal static string LabelContactInfo {
            get {
                return ResourceManager.GetString("LabelContactInfo", resourceCulture);
            }
        }
        
        internal static string LabelDecline {
            get {
                return ResourceManager.GetString("LabelDecline", resourceCulture);
            }
        }
        
        internal static string LabelEventInfo {
            get {
                return ResourceManager.GetString("LabelEventInfo", resourceCulture);
            }
        }
        
        internal static string LabelJobApplicationStatus {
            get {
                return ResourceManager.GetString("LabelJobApplicationStatus", resourceCulture);
            }
        }
        
        internal static string LabelJobAppliedDate {
            get {
                return ResourceManager.GetString("LabelJobAppliedDate", resourceCulture);
            }
        }
        
        internal static string LabelJobBeginner {
            get {
                return ResourceManager.GetString("LabelJobBeginner", resourceCulture);
            }
        }
        
        internal static string LabelJobCompany {
            get {
                return ResourceManager.GetString("LabelJobCompany", resourceCulture);
            }
        }
        
        internal static string LabelJobCompanyIndustry {
            get {
                return ResourceManager.GetString("LabelJobCompanyIndustry", resourceCulture);
            }
        }
        
        internal static string LabelJobCompanyLogo {
            get {
                return ResourceManager.GetString("LabelJobCompanyLogo", resourceCulture);
            }
        }
        
        internal static string LabelJobCompanyName {
            get {
                return ResourceManager.GetString("LabelJobCompanyName", resourceCulture);
            }
        }
        
        internal static string LabelJobDesiredStartDate {
            get {
                return ResourceManager.GetString("LabelJobDesiredStartDate", resourceCulture);
            }
        }
        
        internal static string LabelJobDrivingLicence {
            get {
                return ResourceManager.GetString("LabelJobDrivingLicence", resourceCulture);
            }
        }
        
        internal static string LabelJobExpert {
            get {
                return ResourceManager.GetString("LabelJobExpert", resourceCulture);
            }
        }
        
        internal static string LabelJobExpiry {
            get {
                return ResourceManager.GetString("LabelJobExpiry", resourceCulture);
            }
        }
        
        internal static string LabelJobFilledPositions {
            get {
                return ResourceManager.GetString("LabelJobFilledPositions", resourceCulture);
            }
        }
        
        internal static string LabelJobGeneralInformation {
            get {
                return ResourceManager.GetString("LabelJobGeneralInformation", resourceCulture);
            }
        }
        
        internal static string LabelJobJobPostID {
            get {
                return ResourceManager.GetString("LabelJobJobPostID", resourceCulture);
            }
        }
        
        internal static string LabelJobJobTitle {
            get {
                return ResourceManager.GetString("LabelJobJobTitle", resourceCulture);
            }
        }
        
        internal static string LabelJobJobType {
            get {
                return ResourceManager.GetString("LabelJobJobType", resourceCulture);
            }
        }
        
        internal static string LabelJobLanguagehere {
            get {
                return ResourceManager.GetString("LabelJobLanguagehere", resourceCulture);
            }
        }
        
        internal static string LabelJobLicenceName {
            get {
                return ResourceManager.GetString("LabelJobLicenceName", resourceCulture);
            }
        }
        
        internal static string LabelJobLicences {
            get {
                return ResourceManager.GetString("LabelJobLicences", resourceCulture);
            }
        }
        
        internal static string LabelJobLicenceType {
            get {
                return ResourceManager.GetString("LabelJobLicenceType", resourceCulture);
            }
        }
        
        internal static string LabelJobMinimumExp {
            get {
                return ResourceManager.GetString("LabelJobMinimumExp", resourceCulture);
            }
        }
        
        internal static string LabelJobMonthlySalary {
            get {
                return ResourceManager.GetString("LabelJobMonthlySalary", resourceCulture);
            }
        }
        
        internal static string LabelJobOpenPositions {
            get {
                return ResourceManager.GetString("LabelJobOpenPositions", resourceCulture);
            }
        }
        
        internal static string LabelJobPosted {
            get {
                return ResourceManager.GetString("LabelJobPosted", resourceCulture);
            }
        }
        
        internal static string LabelJobRequiresDrivingLicence {
            get {
                return ResourceManager.GetString("LabelJobRequiresDrivingLicence", resourceCulture);
            }
        }
        
        internal static string LabelJobRolesResponsib {
            get {
                return ResourceManager.GetString("LabelJobRolesResponsib", resourceCulture);
            }
        }
        
        internal static string LabelJobSalary {
            get {
                return ResourceManager.GetString("LabelJobSalary", resourceCulture);
            }
        }
        
        internal static string LabelJobSector {
            get {
                return ResourceManager.GetString("LabelJobSector", resourceCulture);
            }
        }
        
        internal static string LabelJobSkills {
            get {
                return ResourceManager.GetString("LabelJobSkills", resourceCulture);
            }
        }
        
        internal static string LabelJobStatus {
            get {
                return ResourceManager.GetString("LabelJobStatus", resourceCulture);
            }
        }
        
        internal static string LabelJobTitle {
            get {
                return ResourceManager.GetString("LabelJobTitle", resourceCulture);
            }
        }
        
        internal static string LabelJobYears {
            get {
                return ResourceManager.GetString("LabelJobYears", resourceCulture);
            }
        }
        
        internal static string LabelProposeNewTime {
            get {
                return ResourceManager.GetString("LabelProposeNewTime", resourceCulture);
            }
        }
        
        internal static string LabelTimeOptions {
            get {
                return ResourceManager.GetString("LabelTimeOptions", resourceCulture);
            }
        }
        
        internal static string LoginEnterPassword {
            get {
                return ResourceManager.GetString("LoginEnterPassword", resourceCulture);
            }
        }
        
        internal static string LoginEnterUsername {
            get {
                return ResourceManager.GetString("LoginEnterUsername", resourceCulture);
            }
        }
        
        internal static string LoginForgotPassword {
            get {
                return ResourceManager.GetString("LoginForgotPassword", resourceCulture);
            }
        }
        
        internal static string LoginNoAccountSignup {
            get {
                return ResourceManager.GetString("LoginNoAccountSignup", resourceCulture);
            }
        }
        
        internal static string LoginPassText {
            get {
                return ResourceManager.GetString("LoginPassText", resourceCulture);
            }
        }
        
        internal static string LoginUserText {
            get {
                return ResourceManager.GetString("LoginUserText", resourceCulture);
            }
        }
        
        internal static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        internal static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        internal static string MenuJobPosts {
            get {
                return ResourceManager.GetString("MenuJobPosts", resourceCulture);
            }
        }
        
        internal static string MenuPrograms {
            get {
                return ResourceManager.GetString("MenuPrograms", resourceCulture);
            }
        }
        
        internal static string MenuServices {
            get {
                return ResourceManager.GetString("MenuServices", resourceCulture);
            }
        }
        
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        internal static string MobileSMS {
            get {
                return ResourceManager.GetString("MobileSMS", resourceCulture);
            }
        }
        
        internal static string NINorIqama {
            get {
                return ResourceManager.GetString("NINorIqama", resourceCulture);
            }
        }
        
        internal static string RaiseAComplaint {
            get {
                return ResourceManager.GetString("RaiseAComplaint", resourceCulture);
            }
        }
        
        internal static string SearchAlreadyHaveAccount {
            get {
                return ResourceManager.GetString("SearchAlreadyHaveAccount", resourceCulture);
            }
        }
        
        internal static string SearchKeywordText {
            get {
                return ResourceManager.GetString("SearchKeywordText", resourceCulture);
            }
        }
        
        internal static string SearchLocationText {
            get {
                return ResourceManager.GetString("SearchLocationText", resourceCulture);
            }
        }
        
        internal static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        internal static string StartContinueAsGuest {
            get {
                return ResourceManager.GetString("StartContinueAsGuest", resourceCulture);
            }
        }
        
        internal static string StartMoLLogin {
            get {
                return ResourceManager.GetString("StartMoLLogin", resourceCulture);
            }
        }
        
        internal static string StartNLGLogin {
            get {
                return ResourceManager.GetString("StartNLGLogin", resourceCulture);
            }
        }
        
        internal static string StartTab1Text {
            get {
                return ResourceManager.GetString("StartTab1Text", resourceCulture);
            }
        }
        
        internal static string StartTab2GetStarted {
            get {
                return ResourceManager.GetString("StartTab2GetStarted", resourceCulture);
            }
        }
        
        internal static string StartTab2Text {
            get {
                return ResourceManager.GetString("StartTab2Text", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string SubCategory2 {
            get {
                return ResourceManager.GetString("SubCategory2", resourceCulture);
            }
        }
        
        internal static string SubCategory3 {
            get {
                return ResourceManager.GetString("SubCategory3", resourceCulture);
            }
        }
        
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        internal static string TabControlSearchText {
            get {
                return ResourceManager.GetString("TabControlSearchText", resourceCulture);
            }
        }
        
        internal static string TextAboutPageDefault {
            get {
                return ResourceManager.GetString("TextAboutPageDefault", resourceCulture);
            }
        }
        
        internal static string TextAboutPageTitle {
            get {
                return ResourceManager.GetString("TextAboutPageTitle", resourceCulture);
            }
        }
        
        internal static string TextAvailablePrograms {
            get {
                return ResourceManager.GetString("TextAvailablePrograms", resourceCulture);
            }
        }
        
        internal static string TextAvailableServices {
            get {
                return ResourceManager.GetString("TextAvailableServices", resourceCulture);
            }
        }
        
        internal static string TextComplaints {
            get {
                return ResourceManager.GetString("TextComplaints", resourceCulture);
            }
        }
        
        internal static string TextContactPageDefault {
            get {
                return ResourceManager.GetString("TextContactPageDefault", resourceCulture);
            }
        }
        
        internal static string TextContactPageTitle {
            get {
                return ResourceManager.GetString("TextContactPageTitle", resourceCulture);
            }
        }
        
        internal static string TextLanguage {
            get {
                return ResourceManager.GetString("TextLanguage", resourceCulture);
            }
        }
        
        internal static string TextNotLoggedIn {
            get {
                return ResourceManager.GetString("TextNotLoggedIn", resourceCulture);
            }
        }
        
        internal static string TextSettingPageTitle {
            get {
                return ResourceManager.GetString("TextSettingPageTitle", resourceCulture);
            }
        }
        
        internal static string TextSettingsResetPassword {
            get {
                return ResourceManager.GetString("TextSettingsResetPassword", resourceCulture);
            }
        }
        
        internal static string TextSignOut {
            get {
                return ResourceManager.GetString("TextSignOut", resourceCulture);
            }
        }
        
        internal static string TextWatch {
            get {
                return ResourceManager.GetString("TextWatch", resourceCulture);
            }
        }
        
        internal static string TextWatching {
            get {
                return ResourceManager.GetString("TextWatching", resourceCulture);
            }
        }
        
        internal static string WelcomeEmployerSignin {
            get {
                return ResourceManager.GetString("WelcomeEmployerSignin", resourceCulture);
            }
        }
        
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        internal static string JobTypeFilterText {
            get {
                return ResourceManager.GetString("JobTypeFilterText", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_PERM {
            get {
                return ResourceManager.GetString("JOBTYPE_PERM", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_PERM_DESC {
            get {
                return ResourceManager.GetString("JOBTYPE_PERM_DESC", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_CONTR {
            get {
                return ResourceManager.GetString("JOBTYPE_CONTR", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_CONTR_DESC {
            get {
                return ResourceManager.GetString("JOBTYPE_CONTR_DESC", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_MINJOB {
            get {
                return ResourceManager.GetString("JOBTYPE_MINJOB", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_MINJOB_DESC {
            get {
                return ResourceManager.GetString("JOBTYPE_MINJOB_DESC", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_INTERN {
            get {
                return ResourceManager.GetString("JOBTYPE_INTERN", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_INTERN_DESC {
            get {
                return ResourceManager.GetString("JOBTYPE_INTERN_DESC", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_SUMMJOB {
            get {
                return ResourceManager.GetString("JOBTYPE_SUMMJOB", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_SUMMJOB_DESC {
            get {
                return ResourceManager.GetString("JOBTYPE_SUMMJOB_DESC", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_JOBTRNO {
            get {
                return ResourceManager.GetString("JOBTYPE_JOBTRNO", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_JOBTRNO_DESC {
            get {
                return ResourceManager.GetString("JOBTYPE_JOBTRNO_DESC", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_EMPDVNAC {
            get {
                return ResourceManager.GetString("JOBTYPE_EMPDVNAC", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_EMPDVNAC_DESC {
            get {
                return ResourceManager.GetString("JOBTYPE_EMPDVNAC_DESC", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_TAMOJT {
            get {
                return ResourceManager.GetString("JOBTYPE_TAMOJT", resourceCulture);
            }
        }
        
        internal static string JOBTYPE_TAMOJT_DESC {
            get {
                return ResourceManager.GetString("JOBTYPE_TAMOJT_DESC", resourceCulture);
            }
        }
        
        internal static string SortByFilterText {
            get {
                return ResourceManager.GetString("SortByFilterText", resourceCulture);
            }
        }
        
        internal static string SORTBY_DISTANCE {
            get {
                return ResourceManager.GetString("SORTBY_DISTANCE", resourceCulture);
            }
        }
        
        internal static string SORTBY_RELEVANCE {
            get {
                return ResourceManager.GetString("SORTBY_RELEVANCE", resourceCulture);
            }
        }
        
        internal static string SORTBY_SCORE_HIGH {
            get {
                return ResourceManager.GetString("SORTBY_SCORE_HIGH", resourceCulture);
            }
        }
        
        internal static string SORTBY_SCORE_LOW {
            get {
                return ResourceManager.GetString("SORTBY_SCORE_LOW", resourceCulture);
            }
        }
        
        internal static string SORTBY_STARTDATE_RECENT {
            get {
                return ResourceManager.GetString("SORTBY_STARTDATE_RECENT", resourceCulture);
            }
        }
        
        internal static string SORTBY_STARTDATE_FUTURE {
            get {
                return ResourceManager.GetString("SORTBY_STARTDATE_FUTURE", resourceCulture);
            }
        }
        
        internal static string SORTBY_GENDER_MALEFIRST {
            get {
                return ResourceManager.GetString("SORTBY_GENDER_MALEFIRST", resourceCulture);
            }
        }
        
        internal static string SORTBY_GENDER_FEMALEFIRST {
            get {
                return ResourceManager.GetString("SORTBY_GENDER_FEMALEFIRST", resourceCulture);
            }
        }
        
        internal static string WorkTypeFilterText {
            get {
                return ResourceManager.GetString("WorkTypeFilterText", resourceCulture);
            }
        }
        
        internal static string FULLT {
            get {
                return ResourceManager.GetString("FULLT", resourceCulture);
            }
        }
        
        internal static string PART {
            get {
                return ResourceManager.GetString("PART", resourceCulture);
            }
        }
        
        internal static string ShiftTypeFilterText {
            get {
                return ResourceManager.GetString("ShiftTypeFilterText", resourceCulture);
            }
        }
        
        internal static string SHF_Day {
            get {
                return ResourceManager.GetString("SHF_Day", resourceCulture);
            }
        }
        
        internal static string SHF_Night {
            get {
                return ResourceManager.GetString("SHF_Night", resourceCulture);
            }
        }
        
        internal static string SHF_TwoShifts {
            get {
                return ResourceManager.GetString("SHF_TwoShifts", resourceCulture);
            }
        }
        
        internal static string TravelingRequiredFilterText {
            get {
                return ResourceManager.GetString("TravelingRequiredFilterText", resourceCulture);
            }
        }
        
        internal static string TRAV_Day {
            get {
                return ResourceManager.GetString("TRAV_Day", resourceCulture);
            }
        }
        
        internal static string TRAV_Night {
            get {
                return ResourceManager.GetString("TRAV_Night", resourceCulture);
            }
        }
        
        internal static string TRAV_TwoShifts {
            get {
                return ResourceManager.GetString("TRAV_TwoShifts", resourceCulture);
            }
        }
        
        internal static string TeleWorkingFilterText {
            get {
                return ResourceManager.GetString("TeleWorkingFilterText", resourceCulture);
            }
        }
        
        internal static string TELEW {
            get {
                return ResourceManager.GetString("TELEW", resourceCulture);
            }
        }
        
        internal static string NOTELEW {
            get {
                return ResourceManager.GetString("NOTELEW", resourceCulture);
            }
        }
        
        internal static string RequiredEducationFilterText {
            get {
                return ResourceManager.GetString("RequiredEducationFilterText", resourceCulture);
            }
        }
        
        internal static string TCD {
            get {
                return ResourceManager.GetString("TCD", resourceCulture);
            }
        }
        
        internal static string HTC {
            get {
                return ResourceManager.GetString("HTC", resourceCulture);
            }
        }
        
        internal static string LES {
            get {
                return ResourceManager.GetString("LES", resourceCulture);
            }
        }
        
        internal static string ESH {
            get {
                return ResourceManager.GetString("ESH", resourceCulture);
            }
        }
        
        internal static string MSH {
            get {
                return ResourceManager.GetString("MSH", resourceCulture);
            }
        }
        
        internal static string HSH {
            get {
                return ResourceManager.GetString("HSH", resourceCulture);
            }
        }
        
        internal static string BDG {
            get {
                return ResourceManager.GetString("BDG", resourceCulture);
            }
        }
        
        internal static string MDG {
            get {
                return ResourceManager.GetString("MDG", resourceCulture);
            }
        }
        
        internal static string DDG {
            get {
                return ResourceManager.GetString("DDG", resourceCulture);
            }
        }
        
        internal static string DUMMY {
            get {
                return ResourceManager.GetString("DUMMY", resourceCulture);
            }
        }
        
        internal static string SpecializationFilterText {
            get {
                return ResourceManager.GetString("SpecializationFilterText", resourceCulture);
            }
        }
        
        internal static string GenericProgrammesAndQualifications {
            get {
                return ResourceManager.GetString("GenericProgrammesAndQualifications", resourceCulture);
            }
        }
        
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        internal static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        internal static string ArtsAndHumanities {
            get {
                return ResourceManager.GetString("ArtsAndHumanities", resourceCulture);
            }
        }
        
        internal static string SocialSciences {
            get {
                return ResourceManager.GetString("SocialSciences", resourceCulture);
            }
        }
        
        internal static string BusinessAdministration {
            get {
                return ResourceManager.GetString("BusinessAdministration", resourceCulture);
            }
        }
        
        internal static string NaturalSciencesMathematics {
            get {
                return ResourceManager.GetString("NaturalSciencesMathematics", resourceCulture);
            }
        }
        
        internal static string InformationAndCommunicationTechnologies {
            get {
                return ResourceManager.GetString("InformationAndCommunicationTechnologies", resourceCulture);
            }
        }
        
        internal static string EngineeringManufacturingConstruction {
            get {
                return ResourceManager.GetString("EngineeringManufacturingConstruction", resourceCulture);
            }
        }
        
        internal static string AgricultureForestryFisheriesVeterinary {
            get {
                return ResourceManager.GetString("AgricultureForestryFisheriesVeterinary", resourceCulture);
            }
        }
        
        internal static string HealthWelfare {
            get {
                return ResourceManager.GetString("HealthWelfare", resourceCulture);
            }
        }
        
        internal static string GenderFilterText {
            get {
                return ResourceManager.GetString("GenderFilterText", resourceCulture);
            }
        }
        
        internal static string GENDER_M {
            get {
                return ResourceManager.GetString("GENDER_M", resourceCulture);
            }
        }
        
        internal static string GENDER_F {
            get {
                return ResourceManager.GetString("GENDER_F", resourceCulture);
            }
        }
        
        internal static string GENDER_BOTH {
            get {
                return ResourceManager.GetString("GENDER_BOTH", resourceCulture);
            }
        }
        
        internal static string PostedSinceFilterText {
            get {
                return ResourceManager.GetString("PostedSinceFilterText", resourceCulture);
            }
        }
        
        internal static string POSTED_TWODAYS {
            get {
                return ResourceManager.GetString("POSTED_TWODAYS", resourceCulture);
            }
        }
        
        internal static string POSTED_ONEWEEK {
            get {
                return ResourceManager.GetString("POSTED_ONEWEEK", resourceCulture);
            }
        }
        
        internal static string POSTED_TWOWEEKS {
            get {
                return ResourceManager.GetString("POSTED_TWOWEEKS", resourceCulture);
            }
        }
        
        internal static string POSTED_THREEWEEKS {
            get {
                return ResourceManager.GetString("POSTED_THREEWEEKS", resourceCulture);
            }
        }
        
        internal static string POSTED_FOURORMORE {
            get {
                return ResourceManager.GetString("POSTED_FOURORMORE", resourceCulture);
            }
        }
        
        internal static string LabelFilter {
            get {
                return ResourceManager.GetString("LabelFilter", resourceCulture);
            }
        }
        
        internal static string LabelNoKeywordsEntered {
            get {
                return ResourceManager.GetString("LabelNoKeywordsEntered", resourceCulture);
            }
        }
        
        internal static string ButtonNextStep {
            get {
                return ResourceManager.GetString("ButtonNextStep", resourceCulture);
            }
        }
        
        internal static string LabelJobApplicationMethodText {
            get {
                return ResourceManager.GetString("LabelJobApplicationMethodText", resourceCulture);
            }
        }
        
        internal static string LabelJobApplicationRequirementText {
            get {
                return ResourceManager.GetString("LabelJobApplicationRequirementText", resourceCulture);
            }
        }
        
        internal static string LabelJobApplicationSurveyText {
            get {
                return ResourceManager.GetString("LabelJobApplicationSurveyText", resourceCulture);
            }
        }
        
        internal static string LabelJobAttachmentsListText {
            get {
                return ResourceManager.GetString("LabelJobAttachmentsListText", resourceCulture);
            }
        }
        
        internal static string LabelJobAttachmentsText {
            get {
                return ResourceManager.GetString("LabelJobAttachmentsText", resourceCulture);
            }
        }
        
        internal static string LabelJobBenefitsBonusText {
            get {
                return ResourceManager.GetString("LabelJobBenefitsBonusText", resourceCulture);
            }
        }
        
        internal static string LabelJobBenefitsOtherText {
            get {
                return ResourceManager.GetString("LabelJobBenefitsOtherText", resourceCulture);
            }
        }
        
        internal static string LabelJobBenefitsSalaryFromText {
            get {
                return ResourceManager.GetString("LabelJobBenefitsSalaryFromText", resourceCulture);
            }
        }
        
        internal static string LabelJobBenefitsSalaryToText {
            get {
                return ResourceManager.GetString("LabelJobBenefitsSalaryToText", resourceCulture);
            }
        }
        
        internal static string LabelJobBenefitsText {
            get {
                return ResourceManager.GetString("LabelJobBenefitsText", resourceCulture);
            }
        }
        
        internal static string LabelJobContactCompanyLocationText {
            get {
                return ResourceManager.GetString("LabelJobContactCompanyLocationText", resourceCulture);
            }
        }
        
        internal static string LabelJobContactNameText {
            get {
                return ResourceManager.GetString("LabelJobContactNameText", resourceCulture);
            }
        }
        
        internal static string LabelJobContactText {
            get {
                return ResourceManager.GetString("LabelJobContactText", resourceCulture);
            }
        }
        
        internal static string LabelJobLocationAddressText {
            get {
                return ResourceManager.GetString("LabelJobLocationAddressText", resourceCulture);
            }
        }
        
        internal static string LabelJobLocationMobilityNotesText {
            get {
                return ResourceManager.GetString("LabelJobLocationMobilityNotesText", resourceCulture);
            }
        }
        
        internal static string LabelJobLocationMobilityText {
            get {
                return ResourceManager.GetString("LabelJobLocationMobilityText", resourceCulture);
            }
        }
        
        internal static string LabelJobLocationShiftTimeText {
            get {
                return ResourceManager.GetString("LabelJobLocationShiftTimeText", resourceCulture);
            }
        }
        
        internal static string LabelJobLocationTeleworkingText {
            get {
                return ResourceManager.GetString("LabelJobLocationTeleworkingText", resourceCulture);
            }
        }
        
        internal static string LabelJobLocationWorkTimeText {
            get {
                return ResourceManager.GetString("LabelJobLocationWorkTimeText", resourceCulture);
            }
        }
        
        internal static string LabelJobTrainingInstituteText {
            get {
                return ResourceManager.GetString("LabelJobTrainingInstituteText", resourceCulture);
            }
        }
        
        internal static string LabelJobTrainingLocationText {
            get {
                return ResourceManager.GetString("LabelJobTrainingLocationText", resourceCulture);
            }
        }
        
        internal static string LabelJobTrainingNameText {
            get {
                return ResourceManager.GetString("LabelJobTrainingNameText", resourceCulture);
            }
        }
        
        internal static string LabelJobTrainingText {
            get {
                return ResourceManager.GetString("LabelJobTrainingText", resourceCulture);
            }
        }
        
        internal static string LabelJobTrainingValidityText {
            get {
                return ResourceManager.GetString("LabelJobTrainingValidityText", resourceCulture);
            }
        }
        
        internal static string LabelNewJobHeaderText {
            get {
                return ResourceManager.GetString("LabelNewJobHeaderText", resourceCulture);
            }
        }
        
        internal static string LabelNewJobTitleText {
            get {
                return ResourceManager.GetString("LabelNewJobTitleText", resourceCulture);
            }
        }
        
        internal static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        internal static string LabelJobApplications {
            get {
                return ResourceManager.GetString("LabelJobApplications", resourceCulture);
            }
        }
        
        internal static string LabelJobPosts {
            get {
                return ResourceManager.GetString("LabelJobPosts", resourceCulture);
            }
        }
        
        internal static string LabelWatchList {
            get {
                return ResourceManager.GetString("LabelWatchList", resourceCulture);
            }
        }
        
        internal static string ApplicationsInviteToApply {
            get {
                return ResourceManager.GetString("ApplicationsInviteToApply", resourceCulture);
            }
        }
        
        internal static string LabelApplicationsTitle {
            get {
                return ResourceManager.GetString("LabelApplicationsTitle", resourceCulture);
            }
        }
        
        internal static string LabelCandidateInviteTitle {
            get {
                return ResourceManager.GetString("LabelCandidateInviteTitle", resourceCulture);
            }
        }
        
        internal static string CanadidateSendInvite {
            get {
                return ResourceManager.GetString("CanadidateSendInvite", resourceCulture);
            }
        }
        
        internal static string CandidateSendInviteMessage {
            get {
                return ResourceManager.GetString("CandidateSendInviteMessage", resourceCulture);
            }
        }
        
        internal static string CandidateInvitePersonLabel {
            get {
                return ResourceManager.GetString("CandidateInvitePersonLabel", resourceCulture);
            }
        }
        
        internal static string CandidateMessageLabel {
            get {
                return ResourceManager.GetString("CandidateMessageLabel", resourceCulture);
            }
        }
        
        internal static string ButtonSendInvite {
            get {
                return ResourceManager.GetString("ButtonSendInvite", resourceCulture);
            }
        }
        
        internal static string UserDetailsLabel {
            get {
                return ResourceManager.GetString("UserDetailsLabel", resourceCulture);
            }
        }
        
        internal static string UserNINLabel {
            get {
                return ResourceManager.GetString("UserNINLabel", resourceCulture);
            }
        }
        
        internal static string NLGUsernameLabel {
            get {
                return ResourceManager.GetString("NLGUsernameLabel", resourceCulture);
            }
        }
        
        internal static string EmailAddressLabel {
            get {
                return ResourceManager.GetString("EmailAddressLabel", resourceCulture);
            }
        }
        
        internal static string AssignUserRoleLabel {
            get {
                return ResourceManager.GetString("AssignUserRoleLabel", resourceCulture);
            }
        }
        
        internal static string AddUserTitle {
            get {
                return ResourceManager.GetString("AddUserTitle", resourceCulture);
            }
        }
        
        internal static string SaveNewUserButton {
            get {
                return ResourceManager.GetString("SaveNewUserButton", resourceCulture);
            }
        }
        
        internal static string CompanyDescriptionLabel {
            get {
                return ResourceManager.GetString("CompanyDescriptionLabel", resourceCulture);
            }
        }
        
        internal static string CompanyInformationLabel {
            get {
                return ResourceManager.GetString("CompanyInformationLabel", resourceCulture);
            }
        }
        
        internal static string IndustryLabel {
            get {
                return ResourceManager.GetString("IndustryLabel", resourceCulture);
            }
        }
        
        internal static string CompanySizeLabel {
            get {
                return ResourceManager.GetString("CompanySizeLabel", resourceCulture);
            }
        }
        
        internal static string PreferredLanguageLabel {
            get {
                return ResourceManager.GetString("PreferredLanguageLabel", resourceCulture);
            }
        }
        
        internal static string ProfileIDLabel {
            get {
                return ResourceManager.GetString("ProfileIDLabel", resourceCulture);
            }
        }
        
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        internal static string PositionLabel {
            get {
                return ResourceManager.GetString("PositionLabel", resourceCulture);
            }
        }
        
        internal static string MobilePhoneLabel {
            get {
                return ResourceManager.GetString("MobilePhoneLabel", resourceCulture);
            }
        }
        
        internal static string TelephoneNumberLabel {
            get {
                return ResourceManager.GetString("TelephoneNumberLabel", resourceCulture);
            }
        }
        
        internal static string ManageCompanyUsersButton {
            get {
                return ResourceManager.GetString("ManageCompanyUsersButton", resourceCulture);
            }
        }
        
        internal static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        internal static string ContactDetailsLabel {
            get {
                return ResourceManager.GetString("ContactDetailsLabel", resourceCulture);
            }
        }
        
        internal static string EditPersonalDetailsTitle {
            get {
                return ResourceManager.GetString("EditPersonalDetailsTitle", resourceCulture);
            }
        }
        
        internal static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        internal static string SecondNameLabel {
            get {
                return ResourceManager.GetString("SecondNameLabel", resourceCulture);
            }
        }
        
        internal static string ThirdNameLabel {
            get {
                return ResourceManager.GetString("ThirdNameLabel", resourceCulture);
            }
        }
        
        internal static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        internal static string AssignedRoleLabel {
            get {
                return ResourceManager.GetString("AssignedRoleLabel", resourceCulture);
            }
        }
        
        internal static string PrefferedCommunicationLabel {
            get {
                return ResourceManager.GetString("PrefferedCommunicationLabel", resourceCulture);
            }
        }
        
        internal static string SavePersonalDetailsButton {
            get {
                return ResourceManager.GetString("SavePersonalDetailsButton", resourceCulture);
            }
        }
        
        internal static string AccountStatusLabel {
            get {
                return ResourceManager.GetString("AccountStatusLabel", resourceCulture);
            }
        }
        
        internal static string PersonalInformationLabel {
            get {
                return ResourceManager.GetString("PersonalInformationLabel", resourceCulture);
            }
        }
        
        internal static string ManageCompanyUsersTitle {
            get {
                return ResourceManager.GetString("ManageCompanyUsersTitle", resourceCulture);
            }
        }
        
        internal static string RepresentativesTab {
            get {
                return ResourceManager.GetString("RepresentativesTab", resourceCulture);
            }
        }
        
        internal static string RecruitersTab {
            get {
                return ResourceManager.GetString("RecruitersTab", resourceCulture);
            }
        }
        
        internal static string DeleteUserRecruiterMessage {
            get {
                return ResourceManager.GetString("DeleteUserRecruiterMessage", resourceCulture);
            }
        }
        
        internal static string DeleteUserRepresentativeMessage {
            get {
                return ResourceManager.GetString("DeleteUserRepresentativeMessage", resourceCulture);
            }
        }
        
        internal static string AddRecruiterButton {
            get {
                return ResourceManager.GetString("AddRecruiterButton", resourceCulture);
            }
        }
        
        internal static string AddRepresentativeButton {
            get {
                return ResourceManager.GetString("AddRepresentativeButton", resourceCulture);
            }
        }
        
        internal static string PersonalDetailsTitle {
            get {
                return ResourceManager.GetString("PersonalDetailsTitle", resourceCulture);
            }
        }
        
        internal static string EditPersonalDetailsButton {
            get {
                return ResourceManager.GetString("EditPersonalDetailsButton", resourceCulture);
            }
        }
        
        internal static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        internal static string UserTypeLabel {
            get {
                return ResourceManager.GetString("UserTypeLabel", resourceCulture);
            }
        }
        
        internal static string AccountInformationLabel {
            get {
                return ResourceManager.GetString("AccountInformationLabel", resourceCulture);
            }
        }
        
        internal static string LabelApplicationsToText {
            get {
                return ResourceManager.GetString("LabelApplicationsToText", resourceCulture);
            }
        }
        
        internal static string LabelApplicationDateText {
            get {
                return ResourceManager.GetString("LabelApplicationDateText", resourceCulture);
            }
        }
        
        internal static string LabelProgramStatusText {
            get {
                return ResourceManager.GetString("LabelProgramStatusText", resourceCulture);
            }
        }
        
        internal static string LabelAgoText {
            get {
                return ResourceManager.GetString("LabelAgoText", resourceCulture);
            }
        }
        
        internal static string LabelMonthsText {
            get {
                return ResourceManager.GetString("LabelMonthsText", resourceCulture);
            }
        }
        
        internal static string LabelWeeksText {
            get {
                return ResourceManager.GetString("LabelWeeksText", resourceCulture);
            }
        }
        
        internal static string LabelResultsFoundText {
            get {
                return ResourceManager.GetString("LabelResultsFoundText", resourceCulture);
            }
        }
        
        internal static string LabelSearchWelcomeText {
            get {
                return ResourceManager.GetString("LabelSearchWelcomeText", resourceCulture);
            }
        }
        
        internal static string LabelProgramsBeneficiariesText {
            get {
                return ResourceManager.GetString("LabelProgramsBeneficiariesText", resourceCulture);
            }
        }
        
        internal static string LabelProgramsBenefitsText {
            get {
                return ResourceManager.GetString("LabelProgramsBenefitsText", resourceCulture);
            }
        }
        
        internal static string LabelProgramsHowToRegisterText {
            get {
                return ResourceManager.GetString("LabelProgramsHowToRegisterText", resourceCulture);
            }
        }
        
        internal static string LabelProgramsIntroduction {
            get {
                return ResourceManager.GetString("LabelProgramsIntroduction", resourceCulture);
            }
        }
        
        internal static string ContactUsLabel {
            get {
                return ResourceManager.GetString("ContactUsLabel", resourceCulture);
            }
        }
        
        internal static string LabelSearchJobsText {
            get {
                return ResourceManager.GetString("LabelSearchJobsText", resourceCulture);
            }
        }
        
        internal static string LabelSearchLocationText {
            get {
                return ResourceManager.GetString("LabelSearchLocationText", resourceCulture);
            }
        }
        
        internal static string LabelStartPageSkip {
            get {
                return ResourceManager.GetString("LabelStartPageSkip", resourceCulture);
            }
        }
        
        internal static string LabelAddUserTitleText {
            get {
                return ResourceManager.GetString("LabelAddUserTitleText", resourceCulture);
            }
        }
        
        internal static string LabelAboutTermsText {
            get {
                return ResourceManager.GetString("LabelAboutTermsText", resourceCulture);
            }
        }
        
        internal static string LabelAboutVersionText {
            get {
                return ResourceManager.GetString("LabelAboutVersionText", resourceCulture);
            }
        }
        
        internal static string LabelButtonLogOutText {
            get {
                return ResourceManager.GetString("LabelButtonLogOutText", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string LabelProgramsWhocanBenefitText {
            get {
                return ResourceManager.GetString("LabelProgramsWhocanBenefitText", resourceCulture);
            }
        }
    }
}
